### ISSUE TITLE
Answering "normal" results in "easy" on learning cards!

### ISSUE THREAD

**Issue by MartinBernstorff** [julienbaley/AnkiRightHandAnswer#2]
`self._answerCard(3)` is "easy" for learning cards! Serious, breaking bug!

This has caused me quite a bit of grief, as I have a week of cards at too long intervals atm.

**Comment by julienbaley** [comment]
Thanks for reporting this! I'm sorry I haven't replied until now, I've never received a notification for this issue.
So assuming 'k' is 'normal' (3 for review cards, 2 for new cards), my assumption is that:
- 'h' (hard for review) still behaves as normal (i.e. it's a 2 in any case)
- 'l' (easy) foes 4 for review and 3 for new.

Does that sound reasonable?

**Comment by julienbaley** [comment]
@ryqiem 
I have made a fix here. https://github.com/julienbaley/AnkiRightHandAnswer/pull/3
If you have a chance to test, please let me know. I'll merge and publish in a few days otherwise.

**Comment by MartinBernstorff** [comment]
No worries! I migrated to using space+enter, which to me is just as fast and has no risk of running into the same error ;-)

**Comment by julienbaley** [comment]
Ha! I usually use hjkl and space (show answer). Anyway, I'll merge this now, thanks again for the report.
